export const SOMALIA_REGIONS = {
  "Banaadir": [
    "Hodan",
    "Waberi",
    "Hamar Weyne",
    "Hamar Jajab",
    "Yaqshid",
    "Dayniile",
    "Kaxda",
    "Dharkenley",
    "Howlwadaag",
    "Wardhigley (Warta Nabada)",
    "Shibis",
    "Abdiaziz",
    "Shangaani",
    "Karan",
    "Heliwa",
    "Garasbaley",
  ],
  "Woqooyi Galbeed": ["Hargeisa", "Berbera", "Gabiley"],
  "Bari": ["Bosaso", "Qardho", "Iskushuban", "Bandar Beyla", "Alula"],
  "Nugaal": ["Garowe", "Burtinle", "Eyl", "Dangorayo"],
  "Mudug": ["Galkayo", "Hobyo", "Galdogob", "Harardhere", "Jariban"],
  "Galguduud": ["Dhusamareb", "Adaado", "Abudwak", "Guriel", "Ceelbuur", "Ceeldheer"],
  "Hiran": ["Beledweyne", "Buloburde", "Jalalaqsi", "Mataban", "Mahas"],
  "Middle Shabelle": ["Jowhar", "Balcad", "Adale", "Warsheikh", "Mahaday"],
  "Lower Shabelle": ["Merka", "Afgooye", "Wanlaweyn", "Qoryoley", "Barawe", "Kurtunwarey"],
  "Bay": ["Baidoa", "Burhakaba", "Dinsor", "Qansax Dheere"],
  "Bakool": ["Xudur", "Tiyeglow", "Wajid", "Elbarde"],
  "Gedo": ["Garbaharey", "Luuq", "Bardhere", "Doolow", "Beled Hawo", "Elwak"],
  "Middle Juba": ["Bu'aale", "Jilib", "Sakow"],
  "Lower Juba": ["Kismayo", "Afmadow", "Badhadhe", "Jamaame"],
  "Togdheer": ["Burao", "Oodweyne", "Sheikh", "Buuhoodle"],
  "Sanaag": ["Erigavo", "Ceel Afweyn", "Badhan", "Lasqoray"],
  "Sool": ["Las Anod", "Taleh", "Aynaba", "Xudun"],
  "Awdal": ["Borama", "Baki", "Lughaya", "Zeila"],
};
